name: Manual Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
      - name: Build
        run: |
          ./mvnw --batch-mode clean package
      - name: Remove other jars
        run: |
          rm jmx_prometheus_standalone/target/jmx_prometheus_standalone-*-javadoc.jar &&
          rm jmx_prometheus_standalone/target/jmx_prometheus_standalone-*-sources.jar &&
          rm jmx_prometheus_standalone/target/original-jmx_prometheus_standalone-*.jar
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: jmx_prometheus_standalone.jar
          path: jmx_prometheus_standalone/target/jmx_prometheus_standalone-*.jar
          if-no-files-found: error
          retention-days: 1
